# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: OpenAPI Specification 3.x (OASv3) onderzoek
email: dimitri.vanhees@kadaster.nl
description: >- # this means to ignore newlines until "baseurl:"
  Deze pagina is bedoeld om overheids API's te analyseren en zo de status van de adoptie van OASv3 in Nederland te onderzoeken. Tevens biedt deze pagina een aantal handige tools om API descriptions te converteren naar OAS3.
baseurl: "/openapi" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dvh
github_username:  dvh

# Build settings
markdown: kramdown
theme: minima

  # Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
